spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/baizhan
    username: root
    password: 212128
    driver-class-name: com.mysql.cj.jdbc.Driver